Improved the readability of code
open-rmf/rmf_obstacle_detectors pull request #14
Opened 2024-02-25 09:33 UTC by Avisheet

The code enhancements include comments for parameter declarations, pipeline setup, and the thread function for processing OakD spatial detections. The comments provide clarity on parameter purposes, node creation, and debugging visualization using OpenCV. Additionally, proper thread termination in the destructor is ensured, and the ROS 2 component registration process is explained for improved code comprehension.

2024-02-26 02:38 UTC, Yadunund requested changes
Thanks for the PR. Left some feedback. 

> Additionally, proper thread termination in the destructor is ensured, and the ROS 2 component registration process is explained for improved code comprehension.

I don't see any changes relevant to this statement in the PR description. Is this PR still a work in progress?

2024-02-26 02:38 UTC, Yadunund commented on rmf_human_detector_oakd/src/HumanDetector.cpp
> +  // Set properties for camera node
```suggestion
  // Set properties for oak-d camera node
```

2024-02-26 02:38 UTC, Yadunund commented on rmf_human_detector_oakd/src/HumanDetector.cpp
> +  // Setting stereo depth node configs
```suggestion
  // Setting properties for oak-d stereo depth node
```

2024-02-26 02:38 UTC, Yadunund commented on rmf_human_detector_oakd/src/HumanDetector.cpp
> +// Function for the detection of the thread
Not sure what you mean by "detection of the thread"? Did you mean
```suggestion
// Run detection in a separate thread
```

2024-02-26 02:38 UTC, Yadunund commented on rmf_human_detector_oakd/src/HumanDetector.cpp
> +// constructor called
I don't think `constructor called` is the right comment here. It's merely the definition of the constructor.
```suggestion
// Constructor
```

2024-02-26 02:49 UTC, Avisheet commented
Thanks @Yadunund for suggesting the changes. The work is in still progress I'm trying to make the comments so that it will more readable . Further it will help me to understand this project and will be able to contribute in this project

2024-03-17 13:24 UTC, closed without merging

2024-03-17 13:26 UTC, Avisheet commented
I was getting DCO error continuously so i am closing this PR. I will create a new branch to work with.